spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    password: ******
    username: root
#mybatis的配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.dongzj.mb.entity
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
#通用Mapper
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  #设置insert和update中，是否判断字符串类型 != ''
  not-empty: true
  #枚举按简单类型处理
  enum-as-simple-type: true
#分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countsql
  #分页合理化参数，当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: false
  #支持通过Mapper接口参数来传递分页参数，默认值为false。分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  support-methods-arguments: true


